Update

diff --git a/modules/base/files/puppet/97-last-puppet-run b/modules/base/files/puppet/97-last-puppet-run
--- a/modules/base/files/puppet/97-last-puppet-run
+++ b/modules/base/files/puppet/97-last-puppet-run
@@ -1,20 +1,29 @@
 #!/bin/sh
+# SPDX-License-Identifier: Apache-2.0
 # Script that reports when Puppet last ran, in bold if more than an hour ago.
-# from https://github.com/wikimedia/puppet/blob/84c52f5b6b69db1606e25b5e9d8e85e783f3d958/modules/base/files/puppet/97-last-puppet-run
+# Also mentions if it has never run yet
+# From https://github.com/wikimedia/operations-puppet/blob/6d515542d6a216f7d877600992a528c70583e7d6/modules/profile/files/puppet/97-last-puppet-run
+
 set -e
 
+PUPPET_STATE_DIR=/var/lib/puppet/state
+PUPPET_LAST_RUN_PATH="${PUPPET_STATE_DIR}/last_run_report.yaml"
 PATH=/bin:/usr/bin:/usr/local/bin
 LANG=C
-CONFIG_VERSION=$(grep -A1 '^configuration_version:' /opt/puppetlabs/server/data/puppetserver/state/last_run_report.yaml| ruby -ryaml -e 'puts YAML.load(STDIN.read)["configuration_version"]')
-TSLASTPUPPETRUN=$(stat -c %Z /opt/puppetlabs/server/data/puppetserver/state/classes.txt)
-NOW=$(date +%s)
-DELTAMIN=$(((NOW-TSLASTPUPPETRUN)/60))
-BOLD="\\033[1m"
-NORM="\\033[0m"
-LAST_RUN=$(date -d @"${TSLASTPUPPETRUN}")
-if [ $DELTAMIN -gt 60 ]; then
-	MSG="${BOLD}($DELTAMIN minutes ago)${NORM}. $(puppet-enabled || true)"
+BOLD='\033[1m'
+NORM='\033[0m'
+if [ -f "$PUPPET_LAST_RUN_PATH" ]; then
+    CONFIG_VERSION=$(grep -m1 -A1 '^configuration_version:' "$PUPPET_LAST_RUN_PATH"| ruby -ryaml -e 'puts YAML.load(STDIN.read)["configuration_version"]')
+    TSLASTPUPPETRUN=$(stat -c %Z "${PUPPET_STATE_DIR}/classes.txt")
+    NOW=$(date +%s)
+    DELTAMIN=$(((NOW-TSLASTPUPPETRUN)/60))
+    LAST_RUN=$(date -d @"${TSLASTPUPPETRUN}")
+    if [ $DELTAMIN -gt 60 ]; then
+        MSG="${BOLD}($DELTAMIN minutes ago)${NORM}. $(puppet-enabled || true)"
+    else
+        MSG="($DELTAMIN minutes ago). $(puppet-enabled || true)"
+    fi
+    printf "The last Puppet run was at %s %b\\nLast Puppet commit: %s\\n" "${LAST_RUN}" "${MSG}" "${CONFIG_VERSION}"
 else
-	MSG="($DELTAMIN minutes ago). $(puppet-enabled || true)"
+    printf "Puppet %bdoes not seem to have run in this machine%b. Unable to find '%s'.\\n" "$BOLD" "$NORM" "$PUPPET_LAST_RUN_PATH"
 fi
-printf "The last Puppet run was at %s %b\\nLast puppet commit: %s\\n" "${LAST_RUN}" "${MSG}" "${CONFIG_VERSION}"
